ALTER TABLE USER_DATA ADD COLUMN USER_ACCOUNT_ID INT NOT NULL;
ALTER TABLE USER_DATA ADD CONSTRAINT FOREIGN KEY(USER_ACCOUNT_ID) REFERENCES USER_ACCOUNT(ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE EMPLOYEE_DATA ADD COLUMN USER_ACCOUNT_ID INT NOT NULL;
ALTER TABLE EMPLOYEE_DATA ADD CONSTRAINT FOREIGN KEY(USER_ACCOUNT_ID) REFERENCES USER_ACCOUNT(ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE USER_ACCOUNT ADD COLUMN USER_PROFILE_ID INT NOT NULL;
ALTER TABLE USER_ACCOUNT ADD CONSTRAINT FOREIGN KEY(USER_PROFILE_ID) REFERENCES USER_PROFILE(ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE PACKAGE ADD COLUMN PACKAGE_STATE_ID INT NOT NULL;
ALTER TABLE PACKAGE ADD CONSTRAINT FOREIGN KEY(PACKAGE_STATE_ID) REFERENCES PACKAGE_STATE(ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE EMPLOYEE_DATA ADD COLUMN EMPLOYEE_POSITION_ID INT NOT NULL;
ALTER TABLE EMPLOYEE_DATA ADD CONSTRAINT FOREIGN KEY(EMPLOYEE_POSITION_ID) REFERENCES EMPLOYEE_POSITION(ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE LEAVE_DATA ADD COLUMN EMPLOYEE_DATA_ID INT NOT NULL;
ALTER TABLE LEAVE_DATA ADD CONSTRAINT FOREIGN KEY(EMPLOYEE_DATA_ID) REFERENCES EMPLOYEE_DATA(ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE CAR ADD COLUMN CAR_STATE_ID INT NOT NULL;
ALTER TABLE CAR ADD CONSTRAINT FOREIGN KEY(CAR_STATE_ID) REFERENCES CAR_STATE(ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE CAR ADD COLUMN EMPLOYEE_DATA_ID INT NULL;
ALTER TABLE CAR ADD CONSTRAINT FOREIGN KEY(EMPLOYEE_DATA_ID) REFERENCES EMPLOYEE_DATA(ID) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE PACKAGE ADD COLUMN EMPLOYEE_DATA_ID INT NULL;
ALTER TABLE PACKAGE ADD CONSTRAINT FOREIGN KEY(EMPLOYEE_DATA_ID) REFERENCES EMPLOYEE_DATA(ID) ON UPDATE CASCADE ON DELETE SET NULL;


